data:
  name: ECG  # 데이터셋 이름
  data_dir: ./Dataset  # CSV 및 NPY 파일 위치
  train_file: ECG_Train_with_normal.csv
  test_file: ECG_Test_with_anomaly.csv
  category: ECG  # 시계열에서는 큰 의미 없음
  image_size: 1  # 1D 시계열이므로
  seq_len: 750
  batch_size: 64
  DA_batch_size: 16
  test_batch_size: 64
  mask: False  # 시계열에는 segmentation mask 없음
  input_channel: 2  # 다채널 시계열을 위한 채널 수 (예: ch1, ch2)
  num_classes: 2

model:
  DDADS: False  # DDAD 방식 사용 (UNet 대신 DiT)
  checkpoint_dir: ./checkpoints
  checkpoint_name: dit_ts_model
  exp_name: ECG_DDAD_DiT
  feature_extractor: null  # 시계열에는 사용하지 않음
  learning_rate: 3e-4
  weight_decay: 0.05
  epochs: 1000
  load_chp: 0  # 0이면 학습 처음부터 시작, 1 이상이면 저장 weight 불러옴
  DA_epochs: 4
  DA_chp: 4
  v: 0  # feature distance 가중치 (시계열은 픽셀 거리만 사용)
  w: 2  # DDPM 조건 강조 비율
  w_DA: 2
  DLlambda: 0.1
  trajectory_steps: 1000  # 학습 시 전체 노이즈 스텝 수
  test_trajectoy_steps: 250  # 테스트 시 denoising 시작 지점
  test_trajectoy_steps_DA: 250
  skip: 25
  skip_DA: 25
  eta: 1
  beta_start: 0.0001
  beta_end: 0.02
  device: 'cuda'
  save_model: True
  num_workers: 2
  seed: 42
  noise_schedule: "linear"  # 확산 노이즈 스케줄

metrics:
  auroc: True
  pro: False  # segmentation이 없으므로 사용 불가
  misclassifications: True
  visualisation: True

training:
  use_label: True  # train.py에서 label 여부 판단을 위해 필요
